name: amigo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  flutter_contacts: ^1.1.7+1
  get: ^4.6.6
  get_ip_address: ^0.0.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  mobile_number: ^2.1.1
  permission_handler: ^11.3.1
  pin_input_text_field: ^4.5.1
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.5
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

